# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a09b518f3d3dccb293e11f3dfc739574c00a24bee68675bb0a090296bfe44ae3a388c9c614eb6dcbeee9d33078ff3d156cdf8d12d8c8c986bfc26151917e6aa4
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: a09b518f3d3dccb293e11f3dfc739574c00a24bee68675bb0a090296bfe44ae3a388c9c614eb6dcbeee9d33078ff3d156cdf8d12d8c8c986bfc26151917e6aa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_name: <%= ENV["POSTGRESQL_DB"] %>
  db_username: <%= ENV["POSTGRESQL_USER"] %>
  db_password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  db_host: <%= ENV["POSTGRESQL_HOST"] %>
  db_port: <%= ENV["POSTGRESQL_PORT"] %>
  db_uri: <%= ENV["POSTGRESQL_URI"] %>
  tsw_email_password: <%= ENV["TSW_EMAIL_PASSWORD"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  new_relic_key: <%= ENV["NEW_RELIC_KEY"] %>
